### ISSUE TITLE
program immedaitely closing on launch, if HD2 is running

### ISSUE THREAD

**Issue by PatrykBiernacki** [spyoungtech/helldivers2-macros#12]

**Comment by PatrykBiernacki** [comment]
Command window shows for split second.

**Comment by spyoungtech** [comment]
Can you try starting the program from command prompt? That should allow you to see an error message, hopefully.

**Comment by PatrykBiernacki** [comment]
Traceback (most recent call last):
  File "hd2_macros\__main__.py", line 4, in <module>
  File "hd2_macros\macro.py", line 108, in main
  File "hd2_macros\config.py", line 65, in read_config
  File "tomllib\_parser.py", line 66, in load
  File "tomllib\_parser.py", line 102, in loads
  File "tomllib\_parser.py", line 326, in key_value_rule
  File "tomllib\_parser.py", line 369, in parse_key_value_pair
  File "tomllib\_parser.py", line 598, in parse_value
  File "tomllib\_parser.py", line 409, in parse_one_line_basic_str
  File "tomllib\_parser.py", line 575, in parse_basic_str
  File "tomllib\_parser.py", line 494, in parse_basic_str_escape
tomllib.TOMLDecodeError: Unescaped '\' in a string (at line 24, column 35)
[13164] Failed to execute script '__main__' due to unhandled exception!

**Comment by spyoungtech** [comment]
It sounds like you may have a problem in the config.toml -- the latest version of the default config file doesn't have anything meaningful on line 24, so I'm guessing you're using your own TOML file that has some kind of syntax error in it.

You can use sites like [this one](https://www.toml-lint.com/) to validate your TOML file and try to fix any issues. Or if you can provide it here, I can try and help spot the issue.

**Comment by PatrykBiernacki** [comment]
Line 24 is:
autohotkey_executable_path = "C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe"

**Comment by PatrykBiernacki** [comment]
it started working once i commented this line. thanks for help.
